baseURL = "https://profgaelle.com/"
theme = "hugo-goa"
languageCode = "en-gb"
title = "Gaëlle Vallée-Tourangeau | Behavioural Science Research"
enableRobotsTXT = true
publishDir = "public"

# Google Analytics
googleAnalytics = "G-8W2D7KLBJC"

[params]
author = "Gaëlle Vallée-Tourangeau"
intro = "Professor of Behavioural Science"
description = "Expert in behavioural science and decision-making research, specialising in how heuristics and cognitive biases influence real-world choices. Leading research in experimental psychology and choice architecture."
authorimage = "headshot.png"

## Site Meta Settings
[params.meta]
description = "Behavioural science researcher exploring how cognitive biases and choice architecture shape decision-making in real-world contexts. Expert in applied experimental psychology and behavioural interventions."
keywords = "behavioural science, decision making, cognitive biases, heuristics, choice architecture, experimental psychology, behavioural interventions, applied psychology, behavioural economics, decision research"

## Social Accounts
[params.social]
github = "profgaelle"
linkedin = "profgaelle"
email = "g.vallee-tourangeau@kingston.ac.uk?subject=Contact%20from%20profgaelle.com"
googlescholar = "G3o05zgAAAAJ"
orcid = "0000-0003-1080-4443"
bluesky = "profgaelle.bsky.social"

## Extras
[params.extra]
copyright = "© 2024. [Gaëlle Vallée-Tourangeau](https://profgaelle.com). [CC BY-NC-ND](http://creativecommons.org/licenses/by-nc-nd/4.0/)."
poweredby = true
highlightjs = true

# Date format (UK style)
dateformat = "2 Jan 2006"

## Main Menu

# [[menu.main]]
# name = "posts"
# weight = 100
# identifier = "posts"
# url = "posts/"

[[menu.main]]
name = "Bio"
identifier = "bio"
weight = 100
url = "bio/"

[[menu.main]]
name = "Publications"
identifier = "publications"
weight = 100
url = "publications/"


# [[menu.main]]
# name = "projects"
# identifier = "projects"
# weight = 300
# url = "projects/"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Custom CSS to change fonts
[params]
customCSS = ["/css/custom.css"]
